version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    hostname: mysqldb
    networks:
      - mindfruit-net
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    networks:
      - mindfruit-net
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/mindfruit-posts-db
    ports:
      - "8080:8080"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

networks:
  mindfruit-net:

volumes:
  db:
